### ISSUE TITLE
Global State Api Url causes SigServ / invalid memory address

### ISSUE THREAD

**Issue by tijno** [deso-protocol/backend#271]
Fresh fully synced node (incl txindex) on latest image (15/01/2022, digest: 105f2589c926)

When enabling GLOBAL_STATE_API_URL in dev.env and doing down+up - the node crashes.

`GLOBAL_STATE_API_URL=node.deso.org`

Log:

```
E0117 14:02:20.310150       1 admin_fees.go:258] Error decoding desoOutputBytes to slice of DeSoOutputs: EOF - default to no additional fees
E0117 14:02:20.310188       1 admin_fees.go:258] Error decoding desoOutputBytes to slice of DeSoOutputs: EOF - default to no additional fees
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x40 pc=0xe51389]

goroutine 1 [running]:
github.com/deso-protocol/backend/routes.(*APIServer).FetchFromExternalGlobalState(0x0, {0x12179b2, 0x1e})
        /deso/src/backend/routes/expose_global_state.go:184 +0x149
github.com/deso-protocol/backend/routes.(*APIServer).GetVerifiedUsernameMap(0xc0006b9c00)
        /deso/src/backend/routes/expose_global_state.go:58 +0x7b
github.com/deso-protocol/backend/routes.(*APIServer).SetVerifiedUsernameMap(0xc0006b9c00)
        /deso/src/backend/routes/server.go:2075 +0x25
github.com/deso-protocol/backend/routes.(*APIServer).SetGlobalStateCache(0xc0006b9c00)
        /deso/src/backend/routes/server.go:2067 +0x9f
github.com/deso-protocol/backend/routes.NewAPIServer(0xc0ac46a300, 0xc0be797e40, 0xc00014b080, 0xc0be7e2480, 0xc0229bc320, 0x1e6e6c0, 0xc04bf97900, 0x8, 0xc0250c8000, 0x0, ...)
        /deso/src/backend/routes/server.go:440 +0x452
github.com/deso-protocol/backend/cmd.(*Node).Start(0xc000dd1d80)
        /deso/src/backend/cmd/node.go:53 +0x3aa
github.com/deso-protocol/backend/cmd.Run(0x1e6ed80, {0x11d2f37, 0x0, 0x0})
        /deso/src/backend/cmd/run.go:34 +0xcb
github.com/spf13/cobra.(*Command).execute(0x1e6ed80, {0x1f45df8, 0x0, 0x0})
        /root/go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:856 +0x5f8
github.com/spf13/cobra.(*Command).ExecuteC(0x1e6eb00)
        /root/go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:960 +0x3ad
github.com/spf13/cobra.(*Command).Execute(...)
        /root/go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:897
github.com/deso-protocol/backend/cmd.Execute()
        /deso/src/backend/cmd/root.go:24 +0x25
main.main()
        /deso/src/backend/main.go:15 +0x17
```

https://github.com/deso-protocol/backend/blob/163258b733076dc508cd2db288c6493eae4adedb/routes/expose_global_state.go#L184

**Comment by maebeam** [comment]
The URL needs to be fully-formed e.g. `GLOBAL_STATE_API_URL=https://node.deso.org`

**Comment by tijno** [comment]
ah thx!
