### ISSUE TITLE
Postgres sync fails on 46631

### ISSUE THREAD

**Issue by kanshi** [deso-protocol/backend#353]
First reported error:
```E0520 20:57:11.489512       1 server.go:1725] Server._handleBlock: Encountered an error processing block <Header: < 46631, 00000000000009f34619f1108617feb354fe8e8d0abef12254f3d252da7cfa87, 1 >, Signer Key: BC1YLh768bVj2R3QpSiduxcvn7ipxF3L3XHsabZYtCGtsinUnNrZvNN>. Disconnecting from peer [ Remote Address: 35.232.92.5:17000 PeerID=4 ]: Error while processing block: : ConnectBlock: : ConnectTransaction: : _connectNFTBid: Error getting bidder balance: : GetSpendableUtxosForPublicKey: balance underflow (236254451029,34049025845311)```

Later stuck on:
```I0520 20:57:22.822307       1 server.go:1731] Server._handleBlock: Received block ( 46631 / 131300 ) from Peer [ Remote Address: 35.232.92.5:17000 PeerID=7 ]
E0520 20:57:22.868491       1 blockchain.go:1380] MarkBlockInvalid: Block height: 46631, Block hash: 00000000000009f34619f1108617feb354fe8e8d0abef12254f3d252da7cfa87, Error: ConnectBlock: : ConnectTransaction: : _connectSubmitPost: : RuleErrorInputSpendsPreviouslySpentOutput
E0520 20:57:22.868510       1 blockchain.go:1381] MarkBlockInvalid: Printing stack trace so error is easy to find: 
E0520 20:57:22.868531       1 blockchain.go:1382] goroutine 48 [running]:
runtime/debug.Stack()
	/usr/lib/go/src/runtime/debug/stack.go:24 +0x65
github.com/deso-protocol/core/lib.(*Blockchain).MarkBlockInvalid(0xc0a66a27e0, 0xc1710ca580, {0xc0a64b4a80, 0x65})
	/deso/src/core/lib/blockchain.go:1382 +0x14a
github.com/deso-protocol/core/lib.(*Blockchain).ProcessBlock(0xc000358460, 0xc0a3efe090, 0xd0)
	/deso/src/core/lib/blockchain.go:2105 +0x1b39
github.com/deso-protocol/core/lib.(*Server)._handleBlock(0xc0002ec6c0, 0xc094491b00, 0xc0a3efe090)
	/deso/src/core/lib/server.go:1796 +0x625
github.com/deso-protocol/core/lib.(*Server)._handlePeerMessages(0xc0002ec6c0, 0xc094491b00)
	/deso/src/core/lib/server.go:2117 +0x1cd
github.com/deso-protocol/core/lib.(*Server).messageHandler(0xc0002ec6c0)
	/deso/src/core/lib/server.go:2160 +0x1ad
created by github.com/deso-protocol/core/lib.(*Server).Start
	/deso/src/core/lib/server.go:2346 +0xb1
E0520 20:57:22.868544       1 blockchain.go:1389] MarkBlockInvalid: Not marking blocks invalid for now because it makes debugging easier
E0520 20:57:22.868553       1 server.go:1725] Server._handleBlock: Encountered an error processing block <Header: < 46631, 00000000000009f34619f1108617feb354fe8e8d0abef12254f3d252da7cfa87, 1 >, Signer Key: BC1YLh768bVj2R3QpSiduxcvn7ipxF3L3XHsabZYtCGtsinUnNrZvNN>. Disconnecting from peer [ Remote Address: 35.232.92.5:17000 PeerID=7 ]: Error while processing block: : ConnectBlock: : ConnectTransaction: : _connectSubmitPost: : RuleErrorInputSpendsPreviouslySpentOutput```

**Comment by tijno** [comment]
@kanshi see https://github.com/deso-protocol/core/issues/352
