### ISSUE TITLE
Error when sync last few blocks

### ISSUE THREAD

**Issue by electro89** [deso-protocol/backend#481]
This is the error i get, and can not fully sync .
@lazynina 
```
E0421 19:27:35.909645   94728 server.go:1743] Server._handleBlock: Encountered an error processing block <Header: < 693243, 00000005038b0d7ab49917d3c3f4a3e9f412969abc292a7c52ac94263f88c2b7, 1 >, Signer Key: BC1YLh768bVj2R3QpSiduxcvn7ipxF3L3XHsabZYtCGtsinUnNrZvNN>. Disconnecting from peer [ Remote Address: 35.192.117.201:18000, DISCONNECTED PeerID=12 ]: Error while processing block: : ProcessBlock: Problem trying to attach block (< TstampSecs: 1682075708, Height: 693242, Hash: 000000035fff20701cf39b11a33bfb47a0aaf94468bd8210e9324c00dc34c60a, ParentHash 000000038088df927d71fcf42763e665df95dac87f2c9c94ae97e2347cd10528, Status: HEADER_VALIDATED | BLOCK_PROCESSED | BLOCK_STORED, CumWork: 265711230887399>) in reorg: ConnectBlock: Parent hash of block being connected does not match tip
I0421 19:27:35.909778   94728 server.go:1749] Server._handleBlock: Received block ( 693244 / 693364 ) from Peer [ Remote Address: 35.192.117.201:18000, DISCONNECTED PeerID=12 ]
E0421 19:27:35.914052   94728 blockchain.go:1384] MarkBlockInvalid: Block height: 693241, Block hash: 000000038088df927d71fcf42763e665df95dac87f2c9c94ae97e2347cd10528, Error: ConnectBlock: error connecting txn #1: ConnectTransaction: Nonce DeSoNonce: ExpirationBlockHeight: 693518, PartialID: 13936308233543830374 has already been used for PKID &[2 53 122 183 201 238 120 142 241 209 209 249 17 57 99 0 58 45 150 159 237 2 206 148 119 143 249 113 92 110 28 128 117]: RuleErrorReusedNonce
E0421 19:27:35.914184   94728 blockchain.go:1385] MarkBlockInvalid: Printing stack trace so error is easy to find: 
E0421 19:27:35.914262   94728 blockchain.go:1386] goroutine 677711 [running]:
runtime/debug.Stack()
	/usr/local/go/src/runtime/debug/stack.go:24 +0x7a
github.com/deso-protocol/core/lib.(*Blockchain).MarkBlockInvalid(0xc000fde7e0, 0xc242754c00, {0xc3adfdb040, 0x138})
	/home/yas/Downloads/deso/core/lib/blockchain.go:1386 +0x1ea
github.com/deso-protocol/core/lib.(*Blockchain).ProcessBlock(0xc000fde7e0, 0xc6a9a99170, 0x1)
	/home/yas/Downloads/deso/core/lib/blockchain.go:2394 +0x5d28
github.com/deso-protocol/core/lib.(*Server)._handleBlock(0xc00016e900, 0xc214600900, 0xc6a9a99170)
	/home/yas/Downloads/deso/core/lib/server.go:1823 +0xb6b
github.com/deso-protocol/core/lib.(*Server)._handlePeerMessages(0xc00016e900, 0xc1f5321740)
	/home/yas/Downloads/deso/core/lib/server.go:2142 +0x27e
github.com/deso-protocol/core/lib.(*Server).messageHandler(0xc00016e900)
	/home/yas/Downloads/deso/core/lib/server.go:2187 +0x2bc
created by github.com/deso-protocol/core/lib.(*Server).Start
	/home/yas/Downloads/deso/core/lib/server.go:2375 +0x116
E0421 19:27:35.915133   94728 blockchain.go:1393] MarkBlockInvalid: Not marking blocks invalid for now because it makes debugging easier
I0421 19:27:35.915150   94728 peer.go:539] StartDeSoMessageProcessor: Cleaning up message queue for peer: [ Remote Address: 35.192.117.201:18000, DISCONNECTED PeerID=12 ]
I0421 19:27:35.915222   94728 peer.go:555] StartDeSoMessageProcessor: Stopping because peer disconnected: [ Remote Address: 35.192.117.201:18000, DISCONNECTED PeerID=12 ]

```

**Comment by electro89** [comment]
This is the script now running, is this correct?
@lazynina 

```
#!/usr/bin/env bash

DATE=`date +%Y%m%d-%H:%M:%S-%N`

# Seeds. This is the account corresponding to the public key below.
# * Mnemonic:
#   * verb find card ship another until version devote guilt strong lemon six
# * DeSo public keys:
#   * BC1YLg7Bk5sq9iNY17bAwoAYiChLYpmWEi6nY6q5gnA1UQV6xixHjfV
#   * tBCKVERmG9nZpHTk2AVPqknWc1Mw9HHAnqrTpW1RnXpXMQ4PsQgnmV
# * Bitcoin burn addresses:
#   * mhziDsPWSMwUqvZkVdKY92CjesziGP3wHL
#   * 13UkvpJXdLWE4p68n4MAK6zQntQ1RHixyM

rm /tmp/main.*.log

# "-gcflags=”all=-N -l" was added to get GoLand debugger (Delve) to work, see
# https://blog.jetbrains.com/go/2019/02/06/debugging-with-goland-getting-started/
#
# "If you are running with Go 1.10 or newer, you need to add ` -gcflags=”all=-N -l” `
# to the ` go build ` command."

(cd ../../ && go build -o backend -gcflags="all=-N -l" main.go && ./backend run \
  --glog-v=0 \
  --glog-vmodule="*api*=0,*bitcoin_manager*=2,*balance*=0,*frontend*=0,*peer*=0,*addr*=0,*network*=0,*utils*=0,*connection*=0,*main*=0,server*=0,*mempool*=0,*miner*=0,*blockchain*=0,*block_producer*=1" \
  --testnet=true  \
  --api-port=18001 \
  --protocol-port=18000 \
  --txindex=true \
  --admin-public-keys=* \
  --super-admin-public-keys=* \
  --num-mining-threads=1 \
  --starter-deso-seed='road congress client market couple bid risk escape artwork rookie artwork food' \
  --data-dir=/tmp/n0_test_00000 \
  --access-control-allow-origins=http://localhost:4200,http://localhost:80,http://localhost:8080,http://localhost:18002,http://localhost:4201,http://localhost:18001 \
  --secure-header-allow-hosts=localhost:4200 \
  --secure-header-development=true \
  --block-cypher-api-key=092dae962ea44b02809a4c74408b42a1 \
  --min-satoshis-for-profile=0 \
  --expose-global-state=true \
  --show-processing-spinners=true \
  --hypersync=true \
  --sync-type=blocksync \
  --trusted-block-producer-public-keys= \
  --miner-public-keys=tBCKWyhSkpkkmWowATBaCWTUFT98qEnTrwixAN5KJxrm3hKpH14AGJ \
  --block-producer-seed='secret' \
  --metamask-airdrop-deso-nanos-amount=1000)
```

**Comment by lazynina** [comment]
@electro89 - this looks correct! Thanks for helping us identify an issue with hypersync here. The hypersync approach should be resolved shortly

**Comment by lazynina** [comment]
> now it is working
> 
> @lazynina 

Ok I'm going to close this issue then.
