### ISSUE TITLE
Fresh sync on v3.4.0 - postgres / archival failure at block 2

### ISSUE THREAD

**Issue by StarGeezerPhil** [deso-protocol/backend#483]
Has anyone else done a fresh archival/postgres resync since the balance model fork?

Bit of tidying here and spinning up a new container, but the fresh sync seems to be failing at block 2:

```
I0428 17:03:16.404422       1 server.go:769] Received header bundle with 2000 headers in state SYNCING_HEADERS from peer [ Remote Address: 35.232.92.5:17000 PeerID=1 ]. Downloaded ( 220000 / 227856 ) total headers
I0428 17:03:16.867796       1 server.go:769] Received header bundle with 2000 headers in state SYNCING_HEADERS from peer [ Remote Address: 35.232.92.5:17000 PeerID=1 ]. Downloaded ( 222000 / 227856 ) total headers
I0428 17:03:17.282177       1 base.go:246] Refreshing exchange rate...
I0428 17:03:17.316711       1 server.go:769] Received header bundle with 2000 headers in state SYNCING_HEADERS from peer [ Remote Address: 35.232.92.5:17000 PeerID=1 ]. Downloaded ( 224000 / 227856 ) total headers
I0428 17:03:17.824090       1 server.go:769] Received header bundle with 1856 headers in state SYNCING_HEADERS from peer [ Remote Address: 35.232.92.5:17000 PeerID=1 ]. Downloaded ( 226000 / 227856 ) total headers
I0428 17:03:18.211972       1 server.go:1749] Server._handleBlock: Received block ( 1 / 227856 ) from Peer [ Remote Address: 35.232.92.5:17000 PeerID=1 ]
I0428 17:03:18.325365       1 base.go:185] Blockchain exchange rate: 1400 [1400 1400 1400 1400 1400 1400 1400 1400 1400 1400]
I0428 17:03:18.325422       1 base.go:250] Blockchain.com price (USD cents): 1400
I0428 17:03:18.495626       1 base.go:257] Coinbase price (USD Cents): 1416
I0428 17:03:18.495661       1 base.go:286] Final exchange rate: 1420
I0428 17:03:18.801934       1 server.go:1749] Server._handleBlock: Received block ( 2 / 227856 ) from Peer [ Remote Address: 35.232.92.5:17000 PeerID=1 ]
E0428 17:03:18.833151       1 blockchain.go:1384] MarkBlockInvalid: Block height: 2, Block hash: 000001042936d7033dd82ec5f27305c3bc69862dd800e15a3803a8a04e5a5e4c, Error: ConnectBlock: error connecting txn #1: RuleErrorBalanceChangeGreaterThanZero
E0428 17:03:18.833197       1 blockchain.go:1385] MarkBlockInvalid: Printing stack trace so error is easy to find: 
E0428 17:03:18.833232       1 blockchain.go:1386] goroutine 83 [running]:
runtime/debug.Stack()
        /usr/lib/go/src/runtime/debug/stack.go:24 +0x65
github.com/deso-protocol/core/lib.(*Blockchain).MarkBlockInvalid(0x1a398c0?, 0xc14ee52b80, {0xc1a0f55f40, 0x4c})
        /deso/src/core/lib/blockchain.go:1386 +0x12c
github.com/deso-protocol/core/lib.(*Blockchain).ProcessBlock(0xc000b7e000, 0xc1a57075c0, 0xd0?)
        /deso/src/core/lib/blockchain.go:2124 +0x1d85
github.com/deso-protocol/core/lib.(*Server)._handleBlock(0xc000546d80, 0xc000548240, 0xc1a57075c0)
        /deso/src/core/lib/server.go:1814 +0x60d
github.com/deso-protocol/core/lib.(*Server)._handlePeerMessages(0xc000546d80?, 0xc000548240?)
        /deso/src/core/lib/server.go:2142 +0x1dc
github.com/deso-protocol/core/lib.(*Server).messageHandler(0xc000546d80)
        /deso/src/core/lib/server.go:2187 +0x1ad
created by github.com/deso-protocol/core/lib.(*Server).Start
        /deso/src/core/lib/server.go:2375 +0xaf
E0428 17:03:18.833250       1 blockchain.go:1393] MarkBlockInvalid: Not marking blocks invalid for now because it makes debugging easier
E0428 17:03:18.833268       1 server.go:1743] Server._handleBlock: Encountered an error processing block <Header: < 2, 000001042936d7033dd82ec5f27305c3bc69862dd800e15a3803a8a04e5a5e4c, 0 >, Signer Key: NONE>. Disconnecting from peer [ Remote Address: 35.232.92.5:17000 PeerID=1 ]: Error while processing block: : ConnectBlock: error connecting txn #1: RuleErrorBalanceChangeGreaterThanZero
E0428 17:03:18.833566       1 peer.go:1267] ReadDeSoMessage: : ReadMessage: Could not read payload for message type (BLOCK): read tcp 192.168.112.3:59308->35.232.92.5:17000: use of closed network connection
E0428 17:03:18.833611       1 peer.go:1095] Peer.inHandler: Can't read message from peer [ Remote Address: 35.232.92.5:17000, DISCONNECTED PeerID=1 ]: ReadDeSoMessage: : ReadMessage: Could not read payload for message type (BLOCK): read tcp 192.168.112.3:59308->35.232.92.5:17000: use of closed network connection
I0428 17:03:18.864824       1 peer.go:539] StartDeSoMessageProcessor: Cleaning up message queue for peer: [ Remote Address: 35.232.92.5:17000, DISCONNECTED PeerID=1 ]
I0428 17:03:18.864890       1 peer.go:555] StartDeSoMessageProcessor: Stopping because peer disconnected: [ Remote Address: 35.232.92.5:17000, DISCONNECTED PeerID=1 ]
I0428 17:03:21.176591       1 peer.go:1186] Peer.Start: Starting peer [ Remote Address: 35.232.92.5:17000 PeerID=2 ]
I0428 17:03:21.176671       1 peer.go:551] StartDeSoMessageProcessor: Starting for peer [ Remote Address: 35.232.92.5:17000 PeerID=2 ]
I0428 17:03:21.451482       1 server.go:769] Received header bundle with 0 headers in state SYNCING_BLOCKS from peer [ Remote Address: 35.232.92.5:17000 PeerID=2 ]. Downloaded ( 227856 / 227856 ) total headers
I0428 17:03:22.442615       1 server.go:1749] Server._handleBlock: Received block ( 2 / 227856 ) from Peer [ Remote Address: 35.232.92.5:17000 PeerID=2 ]
E0428 17:03:22.488240       1 blockchain.go:1384] MarkBlockInvalid: Block height: 2, Block hash: 000001042936d7033dd82ec5f27305c3bc69862dd800e15a3803a8a04e5a5e4c
```

@mvanhalen @erwin-willems is it just me - anyone else tried a fresh sync?

@lazynina

**Comment by StarGeezerPhil** [comment]
v3.4.1 fix from @lazynina seems to have resolved this 👍
